name: single_sample

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Nextflow
      run: |
        export NXF_VER='19.12.0-edge'
        wget -qO- get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/
    - name: Get sample data
      run: |
        wget https://raw.githubusercontent.com/aertslab/SCENICprotocol/master/example/sample_data_tiny.tar.gz
        tar xvf sample_data_tiny.tar.gz
    - name: Run single_sample test
      run: |
        nextflow run ${GITHUB_WORKSPACE} -profile single_sample,test__single_sample,docker -entry single_sample -ansi-log false
        cat .nextflow.log

